//
//  MainProtocols.swift
//  SampleTouchID
//
//  Created Giovanni Catania on 04/07/17.
//  Copyright © 2017 Giovanni Catania. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainWireframeProtocol: class {
    func presentSensibleDataView(fromView: MainViewProtocol?)
}
//MARK: Presenter -
protocol MainPresenterProtocol: class {

    var interactor: MainInteractorInputProtocol? { get set }
    
    func presentSensibleDataView()
}

//MARK: Interactor -
protocol MainInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MainInteractorInputProtocol: class {

    var presenter: MainInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MainViewProtocol: class {

    var presenter: MainPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
